blog/urls.py
from django.urls import path
from blog import views
from django.conf.urls import url

app_name = 'blog'  # 那个项目下的app
urlpatterns = [
    # url(r'^\w+$', views.index, name='index'),
    # url(r'^$', views.index, name='index'),
    path('', views.index, name='index'),
    path('sign-in/', views.login_index, name='in'),
    path('login/', views.login, name='login'),
    path('sign-up/', views.register_index, name='up'),
    path('register/', views.register, name='register'),
    path('write/', views.write_article, name='write'),
    path('get-write/', views.load_article, name='get_article'),
    path('get-write-tag-others/', views.load_article_tag_category, name='get_tag_category'),
    path('sign-out/', views.logout, name='out'),
    path('write-category/', views.new_category, name='category'),
    path('write-article/', views.new_article, name='article'),
    path('push-option-category/', views.option_one_blog_category, name='option_category'),
    path('save-current/', views.save_current, name='save_current'),
    path('save-current_title/', views.save_current_title, name='save_current_title'),
    path('get-xz-article/', views.load_xz_article, name='get_xz_article'),
    path('modify-wj-name/', views.modify_wj_name, name='modify_wj_name'),
    path('modify-wj-del/', views.modify_wj_del, name='modify_wj_del'),
    path('modify-wz-move/', views.modify_wz_move, name='modify_wz_move'),
    path('modify-wz-del/', views.modify_wz_del, name='modify_wz_del'),
    path('modify-wz-sm/', views.modify_wz_sm, name='modify_wz_sm'),
    path('modify-wz-cancel_push/', views.modify_wz_cancel_push, name='modify_wz_cancel_push'),
    path('write-history/', views.article_history, name='history'),
    path('history-cancel/', views.article_cancel, name='cancel'),
    path('history-recover/', views.article_recover, name='recover'),
    path('push-article/', views.push_article, name='push'),
    path('push-article_update/', views.push_article_update, name='push_update'),
    path('article-show/', views.push_article, name='article-show'),
    path('article-detail-<article_id>-<int:view_count>.html/', views.article_detail, name='article-detail'),
    path('index-bar/', views.index_bar, name='index-bar'),
    path('article_comments/', views.article_comments, name='comments'),
    path('user-<user_name>.html/', views.user_blog, name='user_blog'),
    path('articl-page/', views.article_page, name='page'),
    path('user-setting/', views.user_home, name='user_setting'),
    path('user-setting-base/', views.user_setting_base, name='user_setting_base'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]
# 全局404页面配置
handler404 = views.page_error
handler500 = views.page_error

blog/views.py
from django.shortcuts import render, redirect, HttpResponse, render_to_response
from blog import models
import json
from django.core import exceptions
import pickle
import collections
from blog.utils import mongodb_con
import socket
import time
import os
from django.db.models import F


# Create your views here.


def index(request):
    """
    首页
    :param request:
    :return: 首页
    """
    # 获取当前用户随机字符串
    # 根据随机字符串获取对应信息
    # login = request.session.get('is_sign')
    # user = request.session.get('user')
    article = models.Article.objects.filter(status=0, saveType__gt=1).all()[0:4]  # 加载所有文章
    article_blog_category = models.ArticleBlogCategory.objects.all()  # 加载所有一级栏目
    user = models.User.objects.filter(userName='admin').first()
    data = user_blog_info(user)
    # request.session.clear_expired() 江所有session失效日期小于当前日期删除
    # request.session.clear() #注销的时候使用
    # 加载图文推荐
    article_tj = models.Article.objects.filter(status=0, saveType__gt=1).all()[Page.offset:Page.limit]  # 加载所有文章
    if article_tj:
        Page.offset = Page.limit
        Page.limit = Page.limit + 4
    else:
        Page.offset = 0
        Page.limit = 4
        article_tj = models.Article.objects.filter(status=0, saveType__gt=1).all()[Page.offset:Page.limit]

    return render(request, 'home_main.html',
                  {"article": article, "article_blog_category": article_blog_category, "data": data,
                   "article_tj": article_tj})


def article_page(request):
    offset = request.GET.get("offset")
    limit = request.GET.get("limit")
    article = models.Article.objects.filter(status=0, saveType__gt=1).all()[int(offset):int(limit)]  # 加载所有文章
    article_list = list()
    for item in article:
        c = item.__dict__

        b = item.user.__dict__

        c['user'] = b
        c.pop("_state")
        c["articleTime"] = c["articleTime"].strftime("%Y-%m-%d")
        c['user'].pop("_state")
        article_list.append(c)

    text_json = {'code': '0', 'msg': '', 'data': article_list}
    return HttpResponse(json.dumps(text_json))


def index_bar(request):
    """
    首页侧边bar二级数据
    :param request:
    :return:
    """
    article_blog_category_id = request.GET.get("article_blog_category_id")
    article_blog_category_two = models.ArticleBlogCategoryTwo.objects.filter(
        ArticleBlogCategory__articleBlogCategoryId=article_blog_category_id)
    article_blog_category_two_list = []
    for item in article_blog_category_two:
        article_blog_category_two_list.append({"articleBlogCategoryTwoId": item.articleBlogCategoryTwoId,
                                               "articleBlogCategoryTwoName": item.articleBlogCategoryTwoName})
    print(article_blog_category_two_list)
    text_json = {'code': '0', 'msg': '跟新成功', "data": article_blog_category_two_list}
    return HttpResponse(json.dumps(text_json))


def login_index(request):
    """
    跳转登录首页
    :param request:
    :return: 登录页
    """

    return render(request, 'front/login_sign_in.html')


def login(request):
    """
    用户登录
    :param request:
    :return:首页
    """
    user_name = request.POST.get('user-name')
    user_pwd = request.POST.get('user-pwd')
    user = models.User.objects.filter(userName=user_name, pwd=user_pwd).first()
    if user:
        text_json = {'code': '0', 'msg': '登录成功回首页'}
        # 生成随机字符串
        # 写到浏览器Cookies
        # 写到session
        # 在随机字符串对应字典中设置相关内容
        remember_me = request.POST.get('remember-me')
        # user_pickle = pickle.dumps(user) 江任意数据类型转换为btyts
        # json.dumps(user)可以将任意数据类型转换为json
        # user_dic = user.__dict__
        # user_json = json.dumps(user, default=lambda user: user.__dict__)  # 对象转换json
        # user_dic_state = user_dic['ModelState']
        # user_json = json.dumps(user_dic)
        # print(user_json)
        request.session['user'] = user.userName
        request.session['is_sign'] = True
        # 用户选择是否记住密码，记住一个月免登录，否则浏览器关闭就要登录
        if remember_me:
            request.session.set_expiry(60 * 60 * 24 * 30)
        return HttpResponse(json.dumps(text_json))
    else:
        text_json = {'code': '1', 'msg': '用户名或密码错误'}
        return HttpResponse(json.dumps(text_json))


def user_blog(request, user_name):
    """
    用户主页
    :param request:
    :return:
    """
    user = models.User.objects.filter(userName=user_name).first()
    # 加载所有文章
    article = models.Article.objects.filter(user_id=user.userId, saveType__gt=1, status=0)

    data = user_blog_info(user)

    return render(request, 'user_blog.html',
                  {'article': article, "data": data})


def user_home(reqeust):
    """
    用户信息设置
    :param reqeust:
    :return:
    """
    return render(reqeust, "user_home.html")


def user_setting_base(request):
    """
    用户基础设置
    :param request:
    :return:
    """
    file_obj = request.FILES.get('file')
    nick_name = request.POST.get("nickName")
    say = request.POST.get("say")
    sex = request.POST.get("sex")
    print(os.getcwd())
    # file_path = os.path.join(os.getcwd() + '/blog/static/images', file_obj.name)
    # with open(file_path, 'wb') as f:
    #     for chunk in file_obj.chunks():
    #         f.write(chunk)
    user_name = request.session.get("user")
    models.UserInfo.objects.filter(user__userName=user_name).update(userNickName=nick_name, userSay=say, userSex=sex)
    text_json = {'code': '0', 'msg': '出错了'}
    return HttpResponse(json.dumps(text_json))


def user_blog_info(user):
    """
    加载用户博客信息
    :param user:
    :return:
    """
    # 加载热门文章
    article_hot = models.Article.objects.filter(user_id=user.userId, saveType__gt=1, status=0).order_by(
        '-articleClick').values(
        "articleName", "articleUrl", "articleClick")[0:9]
    # 加载热评文章
    article_hot_comment = models.Article.objects.filter(user_id=user.userId, saveType__gt=1, status=0).order_by(
        '-articleComment').values(
        "articleName", "articleUrl", "articleClick")[0:9]

    # 所有文集
    article_wj = models.ArticleCategory.objects.filter(user_id=user.userId, status=0).all()

    # 加载最新文章
    article_wz = models.Article.objects.filter(user_id=user.userId, saveType__gt=1, status=0).order_by(
        "-articleTime").values("articleName", "articleUrl", "articleClick")[0:9]

    # 用户信息
    user_info = models.UserInfo.objects.filter(user_id=user.userId).values("userMark", "userArticle", "userSay",
                                                                           "userView",
                                                                           "userComment",
                                                                           "userFans", "userLike").first()
    data = {"article_hot": article_hot, "article_hot_comment": article_hot_comment,
            "article_wj": article_wj, "user_info": user_info, "article_wz": article_wz}
    return data


# 用户装饰器
def auth(func):
    def inner(request, *args, **kwargs):
        is_sign = request.session.get("is_sign")
        if not is_sign:
            return redirect('blog:in')
        return func(request, *args, **kwargs)

    return inner


# 文章浏览请求拦截
def article_view(func):
    def view(request, *args, **kwargs):
        print(kwargs)
        models.Article.objects.filter(articleUrl=kwargs['article_id']).update(articleClick=kwargs['view_count'] + 1)
        user = models.Article.objects.filter(articleUrl=kwargs['article_id']).values("user").first()
        user_info = models.UserInfo.objects.filter(user__userId=user["user"]).first()
        user_info.userView = F('userView') + 1
        user_info.save()
        return func(request, *args, **kwargs)

    return view


def logout(request):
    """
    退出登录
    :param request:
    :return:首页
    """
    request.session.clear()  # 清除sessionid日期小于当前日期的session
    request.session.flush()  # 删除当前的会话数据和会话cookie
    return redirect('/')


def register_index(request):
    """
    跳转注册页
    :param request:
    :return:
    """
    return render(request, 'front/login_register.html')


def register(request):
    """
    ajax 注册验证
    :param request:
    :return: 验证信息
    """
    user_name = request.POST.get('user-name')
    user_phone = request.POST.get('user-phone')
    user_pwd = request.POST.get('user-pwd')
    user_count = models.User.objects.filter(userName=user_name).count()
    if user_count > 0:
        json_text = {'code': '1', 'msg': '昵称已被使用,换一个吧'}
        return HttpResponse(json.dumps(json_text))
    else:
        user = models.User(
            userName=user_name,
            pwd=user_pwd,
        )
        user.save()

        models.UserInfo.objects.create(
            userPhone=user_phone,
            user=user
        )
        json_text = {'code': '0', 'msg': '注册成功点击登录'}
        return HttpResponse(json.dumps(json_text))


@auth
def write_article(request):
    """
    跳转写文章页
    :param request:
    :return: 文章页
    """
    # 根据登录用户展示用户类目
    user = request.session.get("user")
    category = models.ArticleCategory.objects.filter(user__userName=user, status=0)
    # django 默认无法解析html会把它转义字符要用这个 {% autoescape off %}才能正常显示
    # 获取当前用户类目下的文章
    # article = models.Article.objects.filter(articleCategory__articleCategoryId=category.articleCategoryId)
    # 获取博客分类
    blog_category = models.ArticleBlogCategory.objects.all()
    return render(request, 'write_article.html', {'category': category, "blog_category": blog_category})


def option_one_blog_category(request):
    """
    选择文章一级类目
    :param request:
    :return: 联动加载二级类目
    """
    one_category_id = request.POST.get("one-category")
    # 数据库通过一级获取二级
    blog_two_cateogry = models.ArticleBlogCategoryTwo.objects.filter(
        ArticleBlogCategory__articleBlogCategoryId=one_category_id)
    category_list = []
    for item in blog_two_cateogry:
        category_list.append({'id': item.articleBlogCategoryTwoId, 'name': item.articleBlogCategoryTwoName})
    json_text = {'code': '0', 'msg': '创建文集成功', "data": category_list}
    return HttpResponse(json.dumps(json_text))


@auth

blog/templates/front/admin.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>wangEditor demo</title>
</head>
<body>
    <div id="editor">
        <p>欢迎使用 <b>wangEditor</b> 富文本编辑器</p>
    </div>

    <!-- 注意， 只需要引用 JS，无需引用任何 CSS ！！！-->
    <script type="text/javascript" src="https://unpkg.com/wangeditor@3.1.1/release/wangEditor.min.js"></script>
    <script type="text/javascript">
        var E = window.wangEditor
        var editor = new E('#editor')
        // 或者 var editor = new E( document.getElementById('editor') )
        editor.create()
    </script>
</body>
</html>

blog/templates/front/login_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'frame/font-awesome-4.7.0/css/font-awesome.css' %}">
</head>
<style>
    body{
        background-color: #f1f1f1;
    }
    .container {
        height: 100%;
        min-height: 750px;
        text-align: center;
        font-size: 14px;
        background-color: #f1f1f1;
    }

    .container .logo {
        position: absolute;
        top: 56px;
        margin-left: 50px;
    }

    .container .login {
        width: 400px;
        margin: 60px auto 0;
        padding: 50px 50px 30px;
        background-color: #fff;
        border-radius: 4px;
        box-shadow: 0 0 8px rgba(0, 0, 0, .1);
        display: inline-block;
        vertical-align: middle;
    }

    .login .title {
        margin: 0 auto 50px;
        padding: 10px;
        font-weight: 400;
        color: #969696;
    }
    .login .title .active{
        font-weight: 700;
        color: #ea6f5a;
        border-bottom: 2px solid #ea6f5a;
    }
    h4{
        font-size: 18px;
    }
    a{
        cursor: pointer;
        text-decoration: none;
        background-color: transparent;
        padding: 10px;
        color: #969696;
    }
    .login .title b{
        padding: 10px;
        font-weight: 700;
    }
</style>
{% block style %}{% endblock %}
<body>
<div class="container">
    <div class="logo">
        <img src="{% static 'images/logo.png' %}">
    </div>
    <div class="login">
        <h4 class="title">
            <div class="normal-title">
                <a id="sign-in-btn" class="active" href="{% url 'blog:in' %}">登录</a>
                <b>&middot;</b>
                <a id="sign-up-btn" class="" href="{% url 'blog:up' %}">注册</a>
            </div>
        </h4>
        <div class="post-data">
            {% block template %}{% endblock %}
        </div>
    </div>
</div>
<script src="{% static 'frame/jquery/dist/jquery.js' %}"></script>
{% block script %}{% endblock %}
</body>
</html>

blog/templates/front/login_sign_in.html
{% extends 'login_index.html' %}

{% block template %}
    <form id="submit">
        <div class="input-sign">
            <input name="user-name" type="text" placeholder="手机号或邮箱"/>
            <i style="position: absolute;left: 25px;top:16px;font-size: 20px" class="fa fa-user-o"></i>
        </div>
        <div class="input-sign">
            <input name="user-pwd" type="password" placeholder="密码">
            <i style="position: absolute;left: 25px;top:16px;font-size: 20px" class="fa fa-lock"></i>
        </div>
        <div class="remember-btn">
            <input type="checkbox"  checked="checked" name="remember-me"
                   id="session_remember_me"><span>记住我</span>
        </div>
        <div class="forget-btn">
            <a class="" data-toggle="dropdown" href="">登录遇到问题?</a>
        </div>
        <button class="sign-in-button" id="sign-in-form-submit-btn" type="button">
            <span id="sign-in-loading"></span>
            登录
        </button>
        <div class="tooltip" style="display: none">
            <span></span>
        </div>
    </form>
{% endblock %}


{% block script %}
    <script>
        $('#sign-in-btn').addClass('active')
        $('#sign-up-btn').removeClass('active')
        $(function () {
            //用户登录
            $('#sign-in-form-submit-btn').click(function () {
                if ($('.input-sign:first-child input').val().trim() == "") {
                    $('form .tooltip span').text('手机号/邮箱不存在,请先注册')
                    $('form .tooltip').slideDown('slow', function () {
                        $(this).hide()
                    })
                } else if ($('.input-sign:eq(1) input').val().trim() == "") {
                    $('form .tooltip span').text('密码不存在,请先注册')
                    $('form .tooltip').slideDown('slow', function () {
                        $(this).hide()
                    })
                } else {
                    $.ajax({
                        type: "POST",
                        url: "{% url 'blog:login' %}",
                        data: $('#submit').serialize(),
                        dataType: "JSON",
                        complete: function (data) {
                            if (data.responseJSON.code == 1) {
                                $('form .tooltip span').text(data.responseJSON.msg)
                                $('form .tooltip').slideDown('slow', function () {
                                    $(this).hide()
                                })
                            }
                            if (data.responseJSON.code == 0) {
                                window.location.href='http://127.0.0.1:8000/'
                            }
                        },
                        error: function (data) {
                            console.log(data)
                        }
                    });
                }

            })


        })
    </script>
{% endblock %}



{% block style %}
    <style>
        .login .input-sign {
            position: relative;

        }

        .login .input-sign input {
            width: 80%;
            height: 50px;
            margin-bottom: 0;
            padding: 4px 12px 4px 35px;
            border: 1px solid #c8c8c8;
            background-color: hsla(0, 0%, 71%, .1);
            vertical-align: middle;
            border-radius: 4px;
            outline: 0;
        }

        .login .remember-btn {
            float: left;
            margin: 15px 0;
        }

        .login .forget-btn {
            float: right;
            position: relative;
            margin: 15px 0;
            font-size: 14px;
        }

        .login .sign-in-button {
            background: #3194d0;
            margin-top: 20px;
            width: 100%;
            padding: 9px 18px;
            font-size: 18px;
            border: none;
            border-radius: 25px;
            color: #fff;
            cursor: pointer;
            outline: none;
            display: block;
            clear: both;
        }

        .login form .tooltip {
            padding: 10px;
            border: 1px solid red;
            position: fixed;
            top: 0;
            margin-left: 100px;
            color: red;
            background-color: #fff;
        }
    </style>
{% endblock %}

blog/templates/front/write_history.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load staticfiles %}
    {% now 'SHORT_DATETIME_FORMAT' as current_year %}
    <link rel="stylesheet" href="{% static 'css/iconfont.css' %}">
    <link rel="stylesheet" href="{% static 'frame/PostbirdAlertBox/css/postbirdAlertBox.css' %}">
    <style>
        ul li {
            list-style: none;
        }

        .container > div.history-list {
            position: fixed;
            width: 19%;
            height: 100%;
            background-color: #FFFFFF;
            border: 1px solid whitesmoke;
            color: #606060;
            overflow-y: scroll;
        }

        .container > div.history-list > div.title {
            border: 1px solid whitesmoke;
        }

        .container > div.history-list > div {

        }

        .container > div.history-list > div:last-child > ul {
            padding: 0;
            margin: 0;
        }

        .container > div.history-list > div:last-child > ul > li {
            padding: 10px;
            border: 1px solid #E6E6E6;
            cursor: pointer;
            font-weight: 800;
            white-space: nowrap;
            word-break: keep-all;
            overflow: hidden;
            /* width: 110%; */
            text-overflow: ellipsis;
        }

        .container > div.history-list > div:last-child > ul > li:hover {
            background-color: #E6E6E6;
        }

        .li-xz {
            background-color: #E6E6E6;
        }

        .container > div.main > div.title {
            position: fixed;
            left: 20%;
            width: 80%;
            background-color: #E6E6E6;
            padding: 20px 0;
            text-align: center;
            line-height: 20px;

        }
        .container > div.main > div.title>h3{
            white-space: nowrap;
            word-break: keep-all;
            overflow: hidden;
            text-overflow: ellipsis;
           text-align: center;
            width: 60%;
            padding: 5px 0;
            margin-left: 20%;
        }

        .container > div.main > div.content {
            position: fixed;
            left: 13%;
            width: 100%;
            height: 80%;
            top: 120px;
            overflow-y: scroll;
        }

        .container > div.main > div.content > div {
            padding: 20px;
            width: 50%;
            margin: 0 auto 20px;
            overflow-y: scroll;

        }

        .container > div.main > div.footer {
            position: fixed;
            left: 20%;
            width:80%;
            bottom: 0;
            background-color: #fff;

        }

        .container > div.main > div.footer > div {
            padding-bottom: 18px;
            margin-left: 40%;
            margin-top: 15px;
        }

        .container > div.main > div.footer > div > span {
            padding: 9px 32px 7px;
            border-radius: 5%;
            color: white;
            cursor: pointer;
            font-weight: 800;
            margin-left: 5px;

        }

        .container > div.main > div.footer > div > span:first-child {
            background-color: #42C02D;
        }

        .container > div.main > div.footer > div > span:last-child {
            background-color: #ED7259;
        }


          .container .tooltip {
            position: fixed;
            color: #FBFBFB;
            display: none;
            right: 50%;
            top: 10px;
            border-radius: 10px;
            padding: 10px;
            border: 1px solid #FBFBFB;
            z-index: 99999999;
            box-shadow: 5px 5px 10px #525252 inset;
            background-color: #525252;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="history-list">
        <div class="title">
            <i class="iconfont icon-shanchu" style="font-size: 25px"></i>
            <span style="display:inline-block;font-size: 25px">回收站</span>
        </div>
        <div>
            <ul>
                {% for item in article %}
                    <li articlId="{{ item.article_uid }}" template="{{ item.content }}">
                        <i class="iconfont icon-wenzhang" style="font-size: 20px;color:black"></i>
                        {{ item.title }}
                    </li>
                {% endfor %}

            </ul>
        </div>
    </div>
    <div class="main">
        <div class="title">
            <h3 style="font-size: 25px"></h3>
            <i id="cha" class="iconfont icon-chadiao"
               style="font-size: 35px;position: absolute;top: 45px;right: 40px;"></i>
        </div>
        <div class="content">
            <div>
            </div>
        </div>
        <div class="footer">
            <div>
                <span id="recover">恢复文章</span>
                <span id="cancel-clear">彻底删除</span>
            </div>
        </div>
    </div>
    <div class="tooltip">
        <i class="iconfont icon-error"></i>
        <span></span>
    </div>
</div>
<script src="{% static 'frame/PostbirdAlertBox/js/postbirdAlertBox.js' %}"></script>
<script src="{% static 'frame/jquery/dist/jquery.js' %}"></script>
<script>
    $(function () {
        //进入默认选择
        init_set()

        //点击每个文章
        $(".container > div.history-list>div:last-child>ul>li").click(function () {
            $(".container > div.history-list>div:last-child>ul>li").removeClass('li-xz')
            $(this).addClass("li-xz")
            $(".main>div.title>h3").text($(this).text())
            var html = $(this).attr("template")
            $(".main>div.content>div").html(html)
        })

        //关闭
        $("#cha").click(function () {
            window.location.href = "{% url 'blog:write' %}"
        })

        //彻底删除文章---这里涉及铭感操作需验证用户信息展示省略
        $("#cancel-clear").click(function () {
            if($(".history-list div:last ul").children().is('li')){
                var article_id = $(".container > div.history-list>div:last-child>ul>li.li-xz").attr("articlid")
                var name = $(".main>div.title>h3").text()
                PostbirdAlertBox.confirm({
                    'content': '确认删除文章《' + name + '》，文章删除后不可恢复。',
                    'okBtn': '确定',
                    'contentColor': 'red',
                    'onConfirm': function () {
                        $.ajax({
                            url: "{% url 'blog:cancel' %}",
                            dataType: 'JSON',
                            method: "POST",
                            data: {"article_id": article_id},
                            success: function (data) {
                                if (data.code == 0) {
                                    window.location.reload()
                                }
                            }

                        })
                    },
                    'onCancel': function () {

                    }
                });
                $(".postbird-box-content div:first-child").hide()
            }else{
                $(".tooltip span").text('内容不能为空')
                $(".tooltip").slideDown(function () {
                    setTimeout(function () {
                        $(".tooltip").hide()
                    }, 2000)

                })
            }

        })

        //恢复文章
        $("#recover").click(function () {
             if($(".history-list div:last ul").children().is('li')){
                 var article_id = $(".container > div.history-list>div:last-child>ul>li.li-xz").attr("articlid")
                 $.ajax({
                     url: "{% url 'blog:recover' %}",
                     dataType: 'JSON',
                     method: "POST",
                     data: {"article_id": article_id},
                     success: function (data) {
                         if (data.code == 0) {
                             window.location.href = "{% url 'blog:write' %}"
                         }
                     }

                 })
             }else{
                 $(".tooltip span").text('内容不能为空')
                 $(".tooltip").slideDown(function () {
                     setTimeout(function () {
                         $(".tooltip").hide()
                     }, 2000)

                 })
             }

        })

        function init_set() {
            $(".container > div.history-list>div:last-child>ul>li:first-child").addClass("li-xz")
            $(".main>div.title>h3").text($(".container > div.history-list>div:last-child>ul>li:first-child").text())
            var html = $(".container > div.history-list>div:last-child>ul>li:first-child").attr("template")
            $(".main>div.content>div").html(html)
        }


    })
</script>
</body>
</html>